# Generated by Django 6.0.1 on 2026-01-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_packages", models.IntegerField()),
                ("license_risks", models.IntegerField()),
                ("abandoned_packages", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PackageRisk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("license", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "last_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("risks", models.JSONField(default=list)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="scanner_api.scan",
                    ),
                ),
            ],
        ),
    ]
